import { ExternalLink, Copy, Check } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { useState } from "react";

export interface GeneratedImage {
  id: string;
  url: string;
  platform: "Midjourney" | "DALL·E" | "Stable Diffusion" | "Leonardo" | "Firefly";
  generatedAt: string;
  aspectRatio?: string;
}

interface ImageResultsDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  promptTitle: string;
  promptContent: string;
  images: GeneratedImage[];
  onCopyPrompt: () => void;
}

const platformColors: Record<string, string> = {
  "Midjourney": "bg-purple-500/20 text-purple-300 border-purple-500/30",
  "DALL·E": "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
  "Stable Diffusion": "bg-orange-500/20 text-orange-300 border-orange-500/30",
  "Leonardo": "bg-blue-500/20 text-blue-300 border-blue-500/30",
  "Firefly": "bg-pink-500/20 text-pink-300 border-pink-500/30",
};

const platformIcons: Record<string, string> = {
  "Midjourney": "🎨",
  "DALL·E": "🤖",
  "Stable Diffusion": "🔥",
  "Leonardo": "🦁",
  "Firefly": "✨",
};

export const ImageResultsDialog = ({
  open,
  onOpenChange,
  promptTitle,
  promptContent,
  images,
  onCopyPrompt,
}: ImageResultsDialogProps) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(promptContent);
    setCopied(true);
    toast.success("Prompt copied to clipboard!", {
      duration: 1500,
      className: "bg-card/90 backdrop-blur-sm border-border",
    });
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl max-h-[90vh] bg-card/95 backdrop-blur-xl border-border/50 p-0 overflow-hidden">
        <DialogHeader className="p-6 pb-0">
          <DialogTitle className="text-foreground text-xl">
            {promptTitle}
          </DialogTitle>
        </DialogHeader>

        <div className="px-6 pb-4">
          {/* Prompt preview */}
          <div className="bg-secondary/30 border border-border/30 rounded-xl p-4 mb-4">
            <p className="text-sm text-muted-foreground line-clamp-3">
              {promptContent}
            </p>
          </div>

          {/* Copy button */}
          <Button
            onClick={handleCopy}
            variant="outline"
            className="w-full mb-4"
          >
            {copied ? (
              <>
                <Check className="h-4 w-4 mr-2" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 mr-2" />
                Copy Prompt
              </>
            )}
          </Button>
        </div>

        {/* Images scroll area */}
        <ScrollArea className="flex-1 px-6 pb-6">
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-medium text-muted-foreground">
                Generated Results ({images.length})
              </h3>
            </div>

            {images.length > 0 ? (
              <div className="space-y-4">
                {images.map((image) => (
                  <div
                    key={image.id}
                    className={cn(
                      "rounded-xl overflow-hidden",
                      "bg-secondary/30 border border-border/30",
                      "hover:border-primary/30 transition-colors"
                    )}
                  >
                    {/* Image */}
                    <div className="relative aspect-[4/3] overflow-hidden">
                      <img
                        src={image.url}
                        alt={`Generated by ${image.platform}`}
                        className="w-full h-full object-cover"
                      />
                    </div>

                    {/* Metadata */}
                    <div className="p-3 flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span
                          className={cn(
                            "px-2 py-1 text-xs font-medium rounded-md border",
                            platformColors[image.platform] || "bg-muted text-muted-foreground"
                          )}
                        >
                          {platformIcons[image.platform]} {image.platform}
                        </span>
                        {image.aspectRatio && (
                          <span className="text-xs text-muted-foreground">
                            {image.aspectRatio}
                          </span>
                        )}
                      </div>
                      <span className="text-xs text-muted-foreground">
                        {new Date(image.generatedAt).toLocaleDateString()}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-12">
                <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-muted/30 flex items-center justify-center">
                  <span className="text-2xl">🖼️</span>
                </div>
                <p className="text-muted-foreground mb-2">No generated images yet</p>
                <p className="text-sm text-muted-foreground/70">
                  Use this prompt to generate images and they'll appear here
                </p>
              </div>
            )}
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
};
